DROP database IF EXISTS `jpa_JBD`;
CREATE database IF NOT EXISTS `jpa_JBD`;
use `jpa_JBD`;


DROP TABLE IF EXISTS `USER_CREDENTIALS`;
DROP TABLE IF EXISTS `USER`;


CREATE TABLE `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_TIME` datetime NOT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `USER_TYPE` varchar(45) NOT NULL,
  `DOB` date NOT NULL,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

CREATE TABLE `USER_CREDENTIALS` (
  `CREDS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `USER_ID` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`CREDS_ID`,`USER_ID`),
  KEY `USER_ID_FK_idx` (`USER_ID`),
  CONSTRAINT `USER_ID_FK` 
  	FOREIGN KEY (`USER_ID`) 
  	REFERENCES `USER` (`ID`) 
  	ON DELETE CASCADE 
  	ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
